import EastIcon from "@mui/icons-material/East";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [nfl, setNfl] = useState([]);

  useEffect(() => {
    axios
      .get("http://127.0.0.1:3050/conferences")
      .then((response) => {
        setNfl(response.data);
      })
      .catch((err) => {
        console.error(`Iiiii deu ruim!!!  ${err}`);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          {nfl.map((afcTeams) => (
            <li key={afcTeams.id}>
              <EastIcon />
              {afcTeams.name}
              <ul>
                {afcTeams.divisions.map((division) => (
                  <li key={division.id}>
                    <EastIcon /> Apelido DIV: {division.alias}
                    {division.teams.map((team) => (
                      <li
                        key={team.id}
                        style={{
                          background: `linear-gradient(100deg,${team.team_colors[0].hex_color},${team.team_colors[1].hex_color})`,
                        }}
                      >
                        <EastIcon />
                        {team.name}
                      </li>
                    ))}
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
